export const LOAD_DISHES = 'LOAD_DISHES';
export const LOAD_DISHES_SUCCESS = 'LOAD_DISHES_SUCCESS';
export const LOAD_DISHES_ERROR = 'LOAD_DISHES_ERROR';
export const INVALIDATE_DISHES = "INVALIDATE_DISHES"
export const ADD_DISH = 'ADD_DISH';
export const DELETE_DISH='DELETE_DISH';
export const ORDER_DISHES="ORDER_DISHES"
