export const LOAD_DISHES = 'LOAD_DISHES';
export const LOAD_DISHES_SUCCESS = 'LOAD_DISHES_SUCCESS';
export const LOAD_DISHES_ERROR = 'LOAD_DISHES_ERROR';
export const INVALIDATE_DISHES = "INVALIDATE_DISHES"
export const REQUEST_POST_DISH = 'REQUEST_POST_DISH';
export const POST_REQUEST_SUCCESS = 'POST_REQUEST_SUCCESS';
export const POST_DISH_ERROR = 'POST_DISH_ERROR';
